# 使用Python官方镜像
FROM python:3.11.8

# 设置工作目录
WORKDIR /app

# 将当前目录下的所有文件复制到工作目录下
COPY . /app

# 安装依赖
RUN pip3 install --no-cache-dir -r /app/requirements.txt
#RUN pip3 install --no-cache-dir -r /app/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# 设置环境变量
ENV PYTHONUNBUFFERED=1
ENV DOCKER_MODE=True

# 运行应用程序
CMD ["python", "app.py"]